### PR TITLE
Changes to support multiple instances of Datatable component per html…

### PR DESCRIPTION
**Pull request by pangweisan**
Hello Vincjo,

   I am new to Github as well as the entire node.js ecosystem. My only exposure to node.js started recently when I tried to build a website using Svelte, that's when I found your table component. It seemed the table component cannot support multiple instances on a single page. I tried some changes using set/get Context and it seemed to work well in my local development.

   Note that the changes I made were strictly constrained to the files in the /src directory, which means they are no longer compatible with the files in the /example directory.

rgds
Pang

### CODE REVIEW

**Comment by vincjo** [comment]
Hello Pang,

Just saw your pull request, it seems you did a huge work. 
Multiple instances is a key feature

I pulled your work locally on a separated branch and i'm trying to mount the Datatable.

Can you give me a sample of code example to instantiate the Datatable ?
Tbh i'm quite lost since the "rows" store is not exported anymore

Otherwise nvm I'll take a closer look this weekend ;)


Thx for your help.
Regards,
vincjo

**Comment by pangweisan** [comment]
Hello Vincjo,
[app.zip](https://github.com/vincjo/svelte-simple-datatables/files/7531418/app.zip)

Attached is the zip of app.svelte where I showed instantiation of 3 instances of Datatable (does the attached zip link work ?). 
Yes, the rows store is no longer exported, because it's hard to manage and use exported store when we need a way to derive multiple instances of an entity using a common exported store. Hence, I made the rows entity a bindable component property that is exported from Datatable. 

The key changes in my attempt to making Datatable supporting multiple instances is using svelte setContext and getContext module. Instead of exporting all the stores, for every instantiation of Datatable I invoked instantiation of new stores and group them into an object using setContext. Hence, all these stores are only accessible from the Datatable instance that initializes the context object. If any child components need to get an access to the stores, they use getContext to retrieve the stores.

I must apologize the pull request shows way more changes that are required to support multiple instances of Datatable than it actually needs, it really  looks unprofessional. I was new to npm, svelte, node js, git, github (am still not good at them), so when the code editor I used was formatting the code unnecessarily, I didn't know how to undo the format changes, so I decided to just commit the changes while keeping the functionality.

Other than setContext and getContext related changes, I also changed data.sortAsc and data.sortDesc to include support for sorting columns with boolean values. Another change I made was in datatable.init(), before the changes, the table columns wouldn't resize by themselves when the table rows were updated. I think I also touched up here and there a bit to make sure functions that need to be aware of table instances work on the correct table by using the exported table name.

Please let me know if there's anything else I could help. Feel free to change the code the way you see appropriate.

If it helps, in my opinion, the core of the changes I made is in Datatable.svelte, in lines below:

	//Initialize context for all stores.
	setContext(key, {})
	initContext()

	const { rows } = getContext(key)
	export const dataRows = rows

	const datatable = getDataTable(name)
	const { options } = getContext(key)

You'll see that in initContext(), the pattern repeats itself for each store that used to be exported, but are not instantiated for each instance of Datatable.svelte, and grouped in a context object.

rgds
Pang

**Comment by vincjo** [comment]
Hello Pang,

Thank you very much for all these precisions.

I was able to understand your work easily and I took the opportunity to update the documentation.
You made the right choices, I don't know of a better way to instantiate the component yet. Despite everything, it remains very simple, which is the goal.
Overall, this was exactly what the component needed to evolve. And using the Svelte context API was the best solution.
So a big thank you

I kept everything you added, including sorting columns with boolean values :thumbsup:

At the same time, I introduced a small breaking change: the ``rowPerPage`` option becomes ``rowsPerPage``

Maybe some bugs will appear, with all these possible use cases, so I'll try to keep an eye on github to fix it faster.



Ty again! :)
regards
vincjo

**Comment by pangweisan** [comment]
Hello Vincjo,

   It's my pleasure to be able to make a little contribution to this repo. I love the functionality the "simple-table" provided, as well as its ease of use. Your clear and concise documentation was also what attracted me to it, and the code was beautifully written. 

rgds
Pang

**Comment by pangweisan** [comment]
Hello Vincjo,

   Regarding the removal of Datatable property "name", and the usage of table id store "id", I would like to share some input with you with regards to my use case. In my current use case, a user can click on another table, or you can imagine it as a menu, and the frontend javascript would insert a text string based on where the user clicks into the filter input box in the Datatable stickyheader, programmatically filtering the Datatable columns. If there are multiple instances of Datatable, then it seems some sort of table identification is needed so that top level user application code could target the table it needs to interact with. Removal of Datatable prop "name" seems making table identification a little more challenging. One might still be able to create the unique reference by creating a container for each Datatable and give the container a unique ID, but this reference is not used anywhere in Datatable module/package.

   I am not sure if this is a valid use case, or if I overlook better ways of uniquely identifying the Datatable instances other than using the old/previous "name" property field.

rgds
Pang

**Comment by vincjo** [comment]
Hello Pang,

The ``id`` store could be set by the user, passing by a component property.
The ``id`` would have a default value (a random string like now) if it's not set in the component.

There are surely some difficulties with the context, but it worth a try

regards
vincjo

**Comment by pangweisan** [comment]
Hello Vincjo,

   I could only see 4 export properties from Datatable.svelte, i.e `data, setting, classList `and `dataRows`, did you mean user could access the` id `store through getContext and setContext ?

rgds
Pang

**Comment by vincjo** [comment]
Sorry, I meant it could be added easily
It's not possible for now

the easiest way would be to add a key to the ``settings`` object

````js
const settings = {
    rowsPerPage: 50,
    id: 'my-first-table',
    ....
}
````
And then pass the ``settings.id`` value to the ``id`` store
Something like that : 

*stores/state.js*
````js
function getId(){
    const getStore = () => {
         const {options} = getContext(key)
         const id = options.get().id ?? 'ssd-' + (Math.random() + 1).toString(36).substring(5)
	const {subscribe } = readable(id)
	return {
        ....
````

Unfortuanately I won't be able to work on it this week :/

**Comment by pangweisan** [comment]
Hello Vincjo,

   That's an excellent idea. I tried the changes you suggested, I need to make some modifications for it to work. Here are my observations:

In Datatable.svelte:
```
	setContext(key, {})
	initContext()

	const { rows } = getContext(key)
	export const dataRows = rows

	const datatable = getDataTable()
	const { id, options } = getContext(key)
	
	$: {
		datatable.setRows(data)
		options.update(settings)
	}
```
The table id store is created/initialized before options store is updated with the table settings passed in from user application, hence` const id = options.get().id ?? 'ssd-' + (Math.random() + 1).toString(36).substring(5)` returns id string from the Math function and this value is populated in the id store. 

What I tried-
In options.js update method, added "id" field in the parsed object.
```
const parsed = {
                    sortable:     typeof opt.sortable       === 'boolean' ? opt.sortable      : true,
                    pagination:   typeof opt.pagination     === 'boolean' ? opt.pagination    : true,
                    rowsPerPage:  typeof opt.rowsPerPage    === 'number'  ? opt.rowsPerPage   : 50,
                    columnFilter: typeof opt.columnFilter   === 'boolean' ? opt.columnFilter  : false, 
                    scrollY:      typeof opt.scrollY        === 'boolean' ? opt.scrollY       : true, 
                    css:          typeof opt.css            === 'boolean' ? opt.css           : true, 
                    id:           typeof opt.id             === 'string'  ? opt.id            : null,
                    labels: labels,
                    blocks: blocks
                }
```

In state.js, I changed the getId() function as below. Note that I needed to change the id store from readable store to writable store, so that the store value could be updated in Datatable.svelte.
```
function getId(){
	const getStore = () => {
		const {options} = getContext(key)
		const idVal = options.get().id ?? 'ssd-' + (Math.random() + 1).toString(36).substring(5)
		const {subscribe, update} = writable(idVal)
		//const {subscribe } = readable('ssd-' + (Math.random() + 1).toString(36).substring(5))
		return {
			subscribe,
			update,
			get: () => {
				let $store
                                id.subscribe(store => $store = store)
                                return $store
			}
		}
	}
	const id = getStore()
	return {id}
}
```

In Datatable.svelte, the changes I made were:
```
$: {
   datatable.setRows(data)
   options.update(settings)
   if (settings.id) {
      id.update(id => options.get().id ?? id)
   }	
}
```

I am not sure if these changes meet your expectation as you made a conscious decision to use a readable store for table id.

rgds
Pang

**Pull request merged**
